<?php

namespace Database\Seeders;

use App\Models\Pengurus;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FasilSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Pengurus::insert([
            [
                'nama' => 'Alifian',
                'jabatan' => 'Fasilitator',
                'foto' => '1.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'M. Luqman A',
                'jabatan' => 'Fasilitator',
                'foto' => '2.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Agus Umar Dani',
                'jabatan' => 'Fasilitator',
                'foto' => '3.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Aisha Sukma',
                'jabatan' => 'Fasilitator',
                'foto' => '4.jpeg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Celly Sardia Devyanna Panjaitan',
                'jabatan' => 'Fasilitator',
                'foto' => '5.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dhiya Shaphira',
                'jabatan' => 'Fasilitator',
                'foto' => '6.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'DORUS G.C.S.F.P. TARANTEIN, B.Sc., B.A English., M.A TESOL',
                'jabatan' => 'Fasilitator',
                'foto' => '7.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'ELYA ELMAGHFIROH',
                'jabatan' => 'Fasilitator',
                'foto' => '8.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Episcia Situmorang',
                'jabatan' => 'Fasilitator',
                'foto' => '9.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Essen Brilian Pangaribuan',
                'jabatan' => 'Fasilitator',
                'foto' => '10.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fadila Abdullah',
                'jabatan' => 'Fasilitator',
                'foto' => '11.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fadillah Mutia',
                'jabatan' => 'Fasilitator',
                'foto' => '12.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Grace Rama Novelyta Br Sembiring',
                'jabatan' => 'Fasilitator',
                'foto' => '13.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Hana Pratiwi',
                'jabatan' => 'Fasilitator',
                'foto' => '14.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ilham Arwani',
                'jabatan' => 'Fasilitator',
                'foto' => '15.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Juliyanti Umabaihi',
                'jabatan' => 'Fasilitator',
                'foto' => '16.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'La Ode Muh Zidane Fajar',
                'jabatan' => 'Fasilitator',
                'foto' => '17.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Lutfi Adi H',
                'jabatan' => 'Fasilitator',
                'foto' => '18.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Maria Kriscintya Ani Bay',
                'jabatan' => 'Fasilitator',
                'foto' => '19.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Mayang Sari',
                'jabatan' => 'Fasilitator',
                'foto' => '20.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Muhammad Bawaidi',
                'jabatan' => 'Fasilitator',
                'foto' => '21.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nur Aziza Supardi',
                'jabatan' => 'Fasilitator',
                'foto' => '22.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nurlaila',
                'jabatan' => 'Fasilitator',
                'foto' => '23.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rahmita Weda',
                'jabatan' => 'Fasilitator',
                'foto' => '24.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rida Aprilyanti Hamid',
                'jabatan' => 'Fasilitator',
                'foto' => '25.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sukron Operma',
                'jabatan' => 'Fasilitator',
                'foto' => '26.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Wirajaya Silaban',
                'jabatan' => 'Fasilitator',
                'foto' => '27.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Zulhilmi',
                'jabatan' => 'Fasilitator',
                'foto' => '28.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Hilda Ningsih',
                'jabatan' => 'Fasilitator',
                'foto' => '29.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Esra Hana M.S',
                'jabatan' => 'Fasilitator',
                'foto' => '30.jpg',
                'kode' => 'fasil',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
